PHACDataHub/cpho-phase2

server/pyproject.toml
server/tests/test_basics.py

This is a small step forward to get us started with testing the server.

Add basic hello world test for server

---

.gcloudignore
ci/Dockerfile
server/cloudbuild.yaml
server/pyproject.toml
server/server/settings.py

This commit adds a cloudbuild.yaml file to the server, and the dockerfile for an image use in that process (in the ci folder)

Add CI setup for the server

---

server/tests/test_indicator_crud.py

Trivial, although the `CreateIndicator` view/form seems to be WIP (no validation, etc) so I expect the shape of the data in this test will change again some time, right? Worth adding tests for the rest of the CRUD steps now?

Fix test_create_indicator post data

---

cloudbuild.yaml

Use versioned .env.prod secrets instead of of :latest Cloud Run deploys

---

server/cpho/jinja2/indicators/upload_indicator.jinja2

added loading button for uploading indicators

loading button for uploading indicators

---

server/.github/dependabot.yml

Added dependabot.yml. Have copied format and times from the [tracker](https://github.com/canada-ca/tracker/blob/master/.github/dependabot.yml#L1-L8) project as I imagine there was a reason for daily 11 am checks. 
Noticed there are a number of configurations we can set while reading through the docs. 
* Do we want to be assigning someone for these PRs?
* How do we want to handle version control between helper functions and this project while maintaining bug fixes for security purposes?

added Dependabot config

---

server/server/settings.py

Use phac_aspc helper `configure_authentication_backends`

---

docker-compose.run-tests.yaml
server/Dockerfile

Nearly trivial, but it might be a pattern worth reusing so I'm making a PR for visibility.

Use docker build arg to select between prod and dev-test dependency sets

---

server/cpho/jinja2/indicators/upload_indicator.jinja2
server/cpho/models/lookups.py
server/cpho/rules.py
server/cpho/views/export_indicators.py
server/cpho/views/upload_indicators.py
server/cpho/views/view_util.py
server/tests/test_export.py
server/tests/test_upload.py

Period info can be added during import/export.
Works with prover versioning too :)

add period to import and export

---

server/cpho/constants.py
server/cpho/jinja2/user_management/create_modify_user.jinja2
server/cpho/jinja2/user_management/user_management_page.jinja2
server/cpho/models/user.py
server/cpho/rules.py
server/cpho/scripts/dev.py
server/cpho/urls.py
server/cpho/util.py
server/cpho/views/user_management.py
server/requirements.txt
server/server/settings.py
server/server/urls.py
server/tests/conftest.py
server/tests/test_user_management.py

Mostly copying ITAP but did it quick and dirty because we'll be canning parts of it later when we (probably) move to indicator-based authorization

add modify/create user views, use real groups for hso/admin/account-managers

---

server/api/util.py
server/requirements.txt
server/requirements_dev.txt

fixes issues introduced in gql PR

Api pr fixes

---

k8s/istio/backendconfig.yaml
k8s/istio/ingress.yaml

Add a backend, with the old WAF policy, to the istio ingress. I might have something wrong in here, someone should adopt this PR from me to double check and test it out.

K8s istio ingress cloud armor WAF configuration

---

server/cpho/jinja2/cpho_macros.jinja2
server/cpho/jinja2/indicators/upload/preview_upload.jinja2
server/cpho/jinja2/indicators/upload/upload_help_modal.jinja2
server/cpho/jinja2/indicators/upload/upload_indicator.jinja2
server/cpho/urls.py
server/cpho/views/upload_indicators.py
server/requirements.txt
server/static/cpho.css
server/tests/test_upload.py
server/tests/test_upload_preview.py

Upon upload, file data gets stored into session storage
the preview upload function displays the data from the session
and then saves the data to the backend.

feat: Upload preview

---

server/cpho/jinja2/indicators/view_indicator_for_period.jinja2

Fixed view indicator for period page in which I removed the "or manage all..." statement and moved the buttons for editing all day and reviewing and submitting all data to the top of the page to make it more visible to the user

Moved buttons to the top

---

server/cpho/jinja2/base.jinja2
server/cpho/jinja2/cpho_macros.jinja2
server/cpho/jinja2/indicators/_progress_bar.jinja2
server/cpho/jinja2/indicators/view_indicator.jinja2
server/cpho/jinja2/indicators/view_indicator_for_period.jinja2
server/cpho/jinja2/review_data.jinja2
server/cpho/views/indicators.py
server/cpho/views/upload_indicators.py
server/static/js/tooltip_accessibility.js
server/tests/test_progress_bar.py

Added progress bar to indicate submission status

Submission progress bar

---

k8s/README.md

Add documentation regarding:
- `k8s/` directory structure / resource organization
- Flux bootstrap
- Sealing secrets to be stored in git
- Installation of other services (istio, cert-manager, etc.)

Add K8s documentation

---

k8s/flux-system/gotk-sync.yaml
k8s/server/sync.yaml

This reverts commit 1f503c1637be8e54bd4eea0c36b143ee9906f1e4.

Revert "update sync manifests pointers (#173)"

---

server/cpho/jinja2/benchmarking/manage_benchmarking_data.jinja2
server/cpho/views/indicator_metadata.py
server/static/cpho.css
server/tests/test_manual_benchamrking_input.py

added form validaiton for the new fields value, standard deviation, and year. Did not add add form validation for labels as it will be switching to a dropdown menu

added form validation for benchmarking

---

server/cpho/jinja2/base.jinja2
server/cpho/jinja2/indicators/upload/upload_help_modal.jinja2
server/cpho/jinja2/login.jinja2
server/requirements_formatting.txt

1.32 had a bug when trying to parse our config, seen in all the other projects

update and run djlint

---

.sops.yaml
k8s/flux-system/alerts/alert-secrets.enc.yaml
k8s/flux-system/kustomization.yaml

- Update project id at relevant places
- Re-encrypt secrets

Configure flux for noble space

---

server/cpho/fixtures/dimension_lookups.yaml
server/cpho/jinja2/indicators/upload/preview_upload.jinja2
server/cpho/models/indicators.py
server/cpho/views/view_util.py
server/tests/test_relevant_dimensions.py
server/tests/test_upload.py
server/tests/test_upload_preview.py

Export and Upload is broken (was broken from before) and new dimensions have been added
Will open up another branch to fix the upload and export

5659 Fixed dimension values for Living arrangement, Income Quintiles and Education household

---

k8s/server/overlays/ephemeral/django/configmap.yaml
k8s/server/overlays/prod/django/configmap.yaml

I just want to add a non-secret environment variable, is this the correct way to do it? Thanks!

extend timeout to 3 days

---

server/cpho/jinja2/base.jinja2
server/cpho/jinja2/changelog/changelog_macros.jinja2
server/cpho/models/user.py

we were showing UUIDs in changelog
Also changed SSO user's display from `Lastname, Firstname (PHAC/ASPC)` to `Firstname Lastname`

use better name display, especially in changelog

---

server/cpho/jinja2/changelog/user_scoped_changelog.jinja2
server/cpho/views/changelog.py
server/cpho/views/view_util.py
server/tests/test_changelog.py

Forgot to add (or broke?) changelog authorization
Also user-scoped changelog was always showing current user, rather than the user whose changelog it is

Changelog authorization

---

server/cpho/views/indicators.py

feat: 5697 added indicator status banners

---

server/cpho/jinja2/base.jinja2

feat: 5694 added session timeout warning dialogue

---

server/cpho/models/indicators.py

CSV fields just don't work in the changelog, I'm working on a longer-term fix in versionator

omit csv field bc it crashes changelog

---

server/cpho/jinja2/base.jinja2
server/cpho/jinja2/indicator_data/manage_indicator_data.jinja2
server/cpho/jinja2/indicators/_progress_bar.jinja2
server/cpho/jinja2/indicators/list_indicators.jinja2
server/cpho/jinja2/indicators/upload/upload_indicator.jinja2
server/cpho/queries.py
server/cpho/urls.py
server/cpho/util.py
server/cpho/views/__init__.py
server/cpho/views/infobase_export.py
server/tests/test_infobase_export.py

Uses phac-helpers' excel utilities to easily produce a 4-sheet (inds, ind-data, benchmarking, trends) semi-normalized export of all relevant data. 
Here's how you access it:

Infobase export

---

server/cpho/jinja2/indicators/_indicator_form.jinja2
server/cpho/rules.py
server/cpho/views/indicators.py
server/static/cpho.css

HSO only field tags and conditional rendering, 
Disabling indicator critical information from non privileged user

HSO only fields

---

k8s/server/overlays/prod/django/hpa.yaml
server/cpho/jinja2/indicators/_indicator_form.jinja2
server/cpho/queries.py
server/cpho/rules.py
server/cpho/views/indicators.py
server/static/cpho.css

Want my horizontal pod scaling tweak on the cluster, all good if #249 and #250 go in to prod at the same time?

Update prod against main

---

k8s/cert-manager/crds/cert-manager.yaml

Release notes at https://cert-manager.io/docs/releases/release-notes/release-notes-1.14/#v1144

Update cert manager to `1.14.4`

---

k8s/server/base/postgres/pg-cluster.yaml

Switch on node maintenance to upgrade k8s cluster

Switch on node maintenance on PG cluster

---

infrastructure/artifactregistry.yaml

feat: clean up policies for artifact registry

---

server/cpho/fixtures/periods.yaml
server/cpho/jinja2/benchmarking/manage_benchmarking_data.jinja2
server/cpho/jinja2/indicator_data/manage_indicator_data.jinja2
server/cpho/jinja2/indicators/view_indicator.jinja2
server/cpho/jinja2/indicators/view_indicator_for_period.jinja2
server/cpho/jinja2/review_indicator_metadata.jinja2
server/cpho/rules.py
server/cpho/translations.py
server/cpho/views/indicator_data.py
server/cpho/views/indicator_metadata.py
server/cpho/views/view_util.py
server/tests/test_manual_data_input.py
server/tests/test_relevant_dimensions.py
server/tests/test_soft_delete.py

Indicator data becomes read only if:
user is program user and period is not current

fix: Read only form for indicator datum

---

server/cpho/jinja2/indicators/upload/preview_upload.jinja2
server/cpho/views/indicator_data.py
server/cpho/views/upload_indicators.py
server/cpho/views/view_util.py
server/tests/test_upload_preview.py

Added check for closed periods.
Also,
Added a class "IndDataCleanMixin"
that helps with validation for indicator datum.
Methods in this class expects input for field and returns validation errors if appropriate.
Reason for making this a class of its own: So that both IndicatorDatumForm and Upload can use the same class to centralize validation logic.
Also reformatted some of the upload code to make it more readable

fix: revamped validation for upload

---

k8s/cert-manager/crds/cert-manager.yaml

Upgrade cert-manager to v1.15.0
See [release notes.](https://github.com/cert-manager/cert-manager/releases/tag/v1.15.0)

chore: upgrade cert manager 1.15.0

---

k8s/cert-manager/crds/cert-manager.yaml

Release notes: https://github.com/cert-manager/cert-manager/releases/tag/v1.15.3

chore: upgrade cert manager v1.15.3

---

k8s/cnpg-system/cnpg-crds.yaml

Release notes: https://github.com/cloudnative-pg/cloudnative-pg/releases/tag/v1.24.0

chore: upgrade cnpg to v1.24.0

---

k8s/cert-manager/crds/cert-manager.yaml

Release notes: https://github.com/cert-manager/cert-manager/releases/tag/v1.16.1

chore: upgrade cert manager to `1.16.1`

---

k8s/cnpg-system/cnpg-crds.yaml
k8s/server/base/postgres/pg-cluster.yaml

Release notes: https://github.com/cloudnative-pg/cloudnative-pg/releases/tag/v1.24.1

chore: upgrade cnpg to `1.24.1`

---

k8s/configconnector-operator-system/autopilot-configconnector-operator.yaml

See release notes: https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.125.0

chore: upgrade KCC to 1.125.0

---

server/server/settings.py

Let's see if this helps the k8s issues we've been having, it shouldn't do us any harm 🤷

fix: turn off connection pooling

---

server/requirements.txt
server/server/open_telemetry_util.py

hopefully this fixes the GCP issues we've been having, which were only ever noticed after I deployed #400

fix: revert weird deps change
