server/README.md
server/pyproject.toml

This commit adds some helper scripts to make server developement nicer. Essentially `pdm db`, `pdm migrate` and `pdm start` all do roughly what you might expect, with the twist that the database is running postgres locally with docker. When you want to shut it down you can run `pdm stop`.
This uses 2 env files... `server.env` for the server and `postgres.env` for the database. Details are in the README.

Add pdm scripts for server dev

---

envoy.yaml

This commit ensures that paths prefixed with /api are forwarded to the server.

Add api route to envoy proxy config

---

server/cpho/models.py
server/cpho/views.py
server/pdm.lock
server/pyproject.toml
server/server/settings.py

Resolved #19. Added ruff with pdm script and fixed max line length errors. Did not fix ruff unused import errors.
Run with command:
```
pdm run linter
```
Probably should move ruff to a .pre-commit-config.yaml in the future CI pipeline.

Added ruff linting to the server

---

.vscode/launch.json

Adds `runserver` and `test` items to the VSCode debugging menu. I always find this useful on django projects, maybe worth doing on other projects and in the template repo (unless y'all really prefer debugging outside of VSCode).

Add .vscode/launch.json for VSCode debugging shortcuts

---

server/cpho/model_factories.py

Fixes `IndicatorDatumFactory`, indirectly fixes `test_indicators_are_versioned`, which was failing with:
> ValueError: Cannot assign "<factory.declarations.SubFactory object at 0x7fa69a23d000>": "IndicatorDatum.dimension_value" must be a "DimensionValue" instance."
Seems `SubFactory` objects have an `evaluate` method that needs to be called (with the right context args, this is a Factory Boy `Declaration` class concept) to instantiate them, but this seems to not be handled when it is returned from a `LazyAttribute`. `Maybe` is an alternative to `LazyAttribute` that is less flexible but is evaluated differently... and just so happens to properly handle the evaluation of returned `Declaration` type classes... yeah, this is annoying, had to crack open the Factory Boy source code to get any …

Fix IndicatorDatumFactory (SubFactory returned from LazyAttribute)

---

.gitignore
.vscode/settings.json
server/.env.dev-public
server/server/settings.py
server/server/settings_util.py
server/tests/test_settings_util.py

As discussed in #50, there's good reason to commit a dev `.env`  to the repo (one less thing for each individual dev to manage/keep in sync, and needs to be available and in-sync for testing in CI too), but there's also a risk that dev's may at some point need to use a sensitive/secret env value for local testing. Committing the dev `.env` file makes it much more likely that such a value could be inadvertently committed in the future, which we do not want.
GitHub secret scanning and push protection are an incomplete mitigation, as they won't be able to detect all possible secret patterns. Better than nothing though.
I'm introducing a further convention here, where a git-ignored `.env.dev-secret` can be used if a dev ever needs to test with a secret value locally (e.g. an API key for a …

Pattern for more safely using sensitive/secret config values in dev

---

server/server/settings_util.py

Realized there actually was a first-party way to merge env files with `decouple`

Simplify implementation of get_project_config

---

deploy/gcloud_init_setup.sh

Will close #83 
Added line in Artifact Registry section of gcloud_init_setup.sh per https://cloud.google.com/artifact-analysis/docs/enable-container-scanning.

Enabled container vulnerability scanning

---

cloudbuild.yaml
deploy/gcloud_env_vars.sh
deploy/gcloud_init_setup.sh
docker-compose.run-tests.yaml
server/Dockerfile

Will close #75 (Upload coverage reports & make more visible), we're adding the reports (in addition to printing them in logs) to the Google Cloud Storage [hopic-test-coverage-reports bucket](https://console.cloud.google.com/storage/browser/hopic-test-coverage-reports;tab=objects?forceOnBucketsSortingFiltering=true&project=phx-01h4rr1468rj3v5k60b1vserd3&prefix=&forceOnObjectsSortingFiltering=false).  The reports are saved under a branch-named folder, as json with filenames of \<timestamp\>-\<commit-sha\>.json.
(Note - chose json so we could easily pull out what we needed if reporting back somewhere like GitHub, but the [flag options are more limited than report](https://coverage.readthedocs.io/en/7.2.7/config.html#json) and it prints out excess lines.)
Unfortunately, as a result, …

Upload test coverage reports

---

.vscode/launch.json
deploy/gcloud_env_vars.sh
deploy/gcloud_init_setup.sh
server/gunicorn.conf.py
server/requirements.txt
server/server/open_telemetry_util.py
server/server/wsgi.py

Related to #84
TODO:
- related steps added to `gcloud_init_setup.sh`
- one step remains a TODO, running `CREATE EXTENSION pgaudit;` inside the DB instance. See #84 
- I figure eventual traces are better than dropped traces, and both are better than significantly slowing down request handling
For reference, here's an example of the benefits from the Trace Explorer perspective. 
The selected span in the trace below is from `Psycopg2Instrumentor`; we always get there for every DB query. The sub-spans of that (Cloud SQL Query, Aggregate, Index Scan) are generated from the DB's logs; this is enabled by the metadata included in each query statement by `sqlcommenter`, which Cloud SQL Query Insights will see in statement logs and use to construct after the fact trace information. Note that …

Cloud SQL observability configuration (DB audit logging, improved OpenTelemetry tracing)

---

server/server/open_telemetry_util.py
server/server/urls.py

A better route than `/` for the automatic GCP health checks to hit. Configured to be ignored by OpenTelemetry instrumentation too.
Related to #65.

Simple healthcheck route

---

server/server/urls.py

Quick and dirty. Not a site we want on search engines anyway, and this _might_ help with the noisy `django.core.exceptions.DisallowedHost` alerts (from legitimate sources at least, nefarious crawlers won't care, so the logging of those will probably need further tuning).

Robots.txt, disalowing all bots

---

deploy/connect_cloud_sql_proxy.sh
deploy/gcloud_cleanup.sh
deploy/gcloud_env_vars.sh
deploy/gcloud_init_setup.sh
deploy/pulumi/package.json
server/.env.dev-public
server/manage.py
server/server/open_telemetry_util.py
server/server/settings.py

Our DB has a private IP, accepting connections only inside the project's virtual private cloud. The Cloud Run app service connects to this with a Serverless VPC Connector. By default, we do not give the DB a public IP at all.
But, especially in the pre-prod phase, we still need to touch the Cloud SQL instance now and then. To enable this, I've added a script that wraps `cloud-sql-proxy` and adds a setup step that temporarily enables a public IP, allow listing only the external IP of the dev machine running the script, as well as an exit trap cleanup step that clears the allow list and disables the public IP. 
Using this script requires you to be logged in as (and re-oauth as, to generate a temporary credential file) a google account with sufficient IAM permissions for patching and …

Add script to support the use of cloud-sql-proxy in dev

---

deploy/connect_cloud_sql_proxy.sh
deploy/gcloud_init_setup.sh

Forgot I'd meant to include backing up as a step in `connect_cloud_sql_proxy.sh`. Following up with that (also constraining the backups to a in-Canada region while I was at it).

Prod DB backups on local connect

---

server/cpho/jinja2/base.jinja2
server/cpho/jinja2/changelog/changelog_macros.jinja2
server/cpho/jinja2/changelog/indicator_scoped_changelog.jinja2
server/cpho/jinja2/changelog/user_scoped_changelog.jinja2
server/cpho/urls.py
server/cpho/views/changelog.py
server/cpho/views/upload_indicators.py
server/tests/test_changelog.py

I thought it would be useful for users to see their changes when they upload a CSV. Unfortunately that is complex but what we can easily do is show them a changelog of all their changes EVER, and naturally the upload changes will be the first changes they see

add user-changelog, redirect to it from successful uploads

---

server/cpho/translations.py
server/server/middleware.py
server/server/settings.py

If there are any exceptional views that don't require login, we'll have to tag them with the mixin or decorator

redirect unauthenticated users to login w/ ?next= param

---

k8s/application/server/deployment.yaml
k8s/application/server/hpa.yaml
server/gunicorn.conf.py
server/server/open_telemetry_util.py
server/server/settings.py
server/server/wsgi.py

Experimental k8s tuning, to see how the application performs when limited to one django server process per pod. Each pod is using the minimum pod-total resources for GKE Autopilot. 
This is probably not ideal, but I think it's worth trying just to learn more to inform future deployment tuning. We'll have to do some load testing against this once deployed, but there's plenty of tools for that.

k8s pod and app process 1 to 1

---

server/cpho/jinja2/base.jinja2
server/cpho/jinja_helpers.py
server/requirements.txt
server/static/cpho.css

Use PHAC logo from `django-phac_aspc-helpers`, tweak the wordmark/footer to look a little better. Closes #49.

Logo and wordmark

---

k8s/application/postgres-sql/cnpg-cm.yaml
k8s/application/postgres-sql/kustomization.yaml
k8s/application/postgres-sql/postgres-cluster.yaml
k8s/certmanager/kustomization.yaml
k8s/flux/kustomization.yaml

Issue: GCP Kubernetes Cluster requests 1CPU and 1GB Memory which lead to high deployment cost.
Fix: Each deployment, pod and cluster has been modified and limits are being added to the allocation to memory and cpu.

Refactoring the CPU and Memory usage for Hopic Project

---

k8s/server/django/deployment.yaml

Add readiness probe at `/healthcheck` endpoint.
Closes #139

Configure `readinessProbe` for server

---

k8s/cert-manager/certificate.yaml
k8s/server/django/deployment.yaml

We stopped using that domain a few weeks back, had it redirecting to the current domain. Recently removed the domain from out alpha DNS repo, so any references to it are now fully deprecated.

Chore: remove prod configuration references to the temporary k8s domain name

---

server/cpho/jinja2/indicators/_indicator_form.jinja2

Using form.media renders the same script tags, but also adds an important attr to the first,
```html
<script src="/static/ckeditor/ckeditor-init.js" data-ckeditor-basepath="/static/ckeditor/ckeditor/" id="ckeditor-init-script"></script>
```

use form.media instead of hardcoded link to generated static/ file

---

k8s/flux-system/gotk-sync.yaml
k8s/server/sync.yaml

tldr;
- add new `gitrepo` resource for `a11y-testing`
- update `server` namespace to reconcile against the new `gitrepo` resource
- point all other namespaces back to reconciling against the `main` branch
In the current scenario, all resources are reconciled against the `a11y-testing` branch. This makes it difficult to make  changes to the kubernetes specific components cause then we'd have to merge to `main` and then to `a11y-testing` to keep things clean.
This PR addresses the problem by adding a new `gitrepo` resource pointing to `a11y-testing` and updating the sync manifest in the `server/` directory to reconcile against the new `gitrepo` resource. In other words, this means all resources other than the ones in `server` namespace reconcile back to the `main` branch and all resources …

Update sync manifests

---

k8s/server/django/secrets.enc.yaml

As mentioned in https://github.com/PHACDataHub/cpho-phase2/issues/159#issuecomment-1852400501, the deployment might require a restart to propagate the updated secret value.
Also, this branch needs to be further merged into `a11y-testing` due to https://github.com/PHACDataHub/cpho-phase2/pull/173.

Update SSO Secret

---

deploy/gcloud_env_vars.sh
k8s/flux-system/gotk-sync.yaml
k8s/server/sync.yaml

tldr;
Reverts PHACDataHub/cpho-phase2#170 to attach the new k8s cluster (in noble-experimentation) to `main`.
The current cluster has been configured to sync against `a11y-testing` branch and we can tear it down once the accessibility testing has been completed.
Going forward, the plan is to utilize the new [noble-experimentation GCP project space](https://console.cloud.google.com/welcome?project=pht-01hhjj7tt0m) to stand up the infrastructure and use `main` branch as it's source of truth. That involves updating the GCP specific components in the manifests to point to the new space, which, will be done is subsequent PRs. [Here's](https://github.com/PHACDataHub/Wiki/wiki/Noble-(Experimentation)-Offering) some more info on noble-experimentation

Revert "Make a11y-testing, temporarily, the image deployment and cluster syncing branch"

---

k8s/cert-manager/crds/kustomization.yaml

Changes:
- Removed Istio Injection
- Changed the minimum pod resources for the deployements
- ~~Changed the images to Chaingaurd~~ (See the [comment](https://github.com/PHACDataHub/cpho-phase2/pull/178#issuecomment-1875800179) )
- Refactored the patches

Updating the cert-manager kustomization

---

server/cpho/jinja_helpers.py
server/server/settings.py
server/tests/test_jinja_helpers.py

Not super well documented on Django's end, and a little wonky, but this is a common feature of many servers/server gateway interfaces and it's Django's prescribed method for hosting a Django app from a sub-resource (path) under a domain. I've left a beefy comment in settings.py to cover the weirder aspects. The env var will only be set in the ephemeral deployments, so none of this impacts prod or local dev.
Well, one caveat to that. Code that modifies the path directly (notably and possibly only `convert_url_other_lang`) needs to understand and account for `SCRIPT_NAME` path components, or else there will be ephemeral deployment specific bugs. Not a big deal though, as I see it. Forgetting to account for it won't impact prod, worst case it's just an obscure foot gun for the obscure …

Support SCRIPT_NAME env var, to enable "ephemeral" dev builds to be hosted from unique paths under a shared subdomain 

---

k8s/cert-manager/crds/kustomization.yaml
k8s/cert-manager/kustomization.yaml
k8s/istio-ingress/gw-certificate.yaml
k8s/istio-ingress/kustomization.yaml
k8s/istio-ingress/sync.yaml

- Update project specific dependencies - project-ids, service account names and load balancer ip.
- Update dependency order
Initially `cert-manager` used to depend on the `istio-ingress` ks, however, this has now been reversed due to fact that we expect the certificate secret to be created before gateway configuration can consume it.
- Clean up comments
Depends on https://github.com/PHACDataHub/dns/pull/56 to work.

Configure ASM and cert-manager for noble

---

k8s/cnpg-system/cnpg-cm.yaml
k8s/cnpg-system/cnpg-crds.yaml
k8s/server/base/django/deployment.yaml
k8s/server/base/postgres/pg-cluster.yaml
k8s/server/overlays/ephemeral/django/configmap.yaml
k8s/server/overlays/ephemeral/django/deployment.yaml
k8s/server/overlays/ephemeral/django/kustomization.yaml
k8s/server/overlays/ephemeral/django/secrets.enc.yaml
k8s/server/overlays/ephemeral/postgres/kustomization.yaml
k8s/server/overlays/prod/django/configmap.yaml
k8s/server/overlays/prod/django/deployment.yaml
k8s/server/overlays/prod/django/kustomization.yaml
k8s/server/overlays/prod/django/secrets.enc.yaml
k8s/server/overlays/prod/postgres/kustomization.yaml
k8s/server/overlays/prod/postgres/pg-cluster.yaml
k8s/server/overlays/prod/postgres/restore/restore-from-k8s-backup-object.yaml
k8s/server/overlays/prod/postgres/restore/restore-from-live-cluster.yaml
k8s/server/overlays/prod/postgres/restore/restore-from-object-storage.yaml
k8s/server/overlays/prod/sync.yaml

- Update `cnpg-system` CRDs
- Update project specific dependencies - project-ids, service account names and re-encrypt secrets.
- Add a `ConfigMap` resource for storing configurations. This is referenced in the **overlay** deployments (not in base) via a `envFrom` key
- Update resources for server pod.
Since the minimum resources for the server pod was causing a scale-up by the HPA in our old cluster, I've bumped up the resources a bit to ensure there's only one replica. The HPA would still "kick-in" if there's a spike in traffic.
- Update resources for postgres cluster pods
Don't exactly remember why but the postgres cluster pods were using `1926Mi` memory. Based on the utilization from the old cluster, I've dialed down the cpu / memory on this.
- Move resources for `istio-proxy` …

Configure server for noble

---

infrastructure/cloudbuild.yaml
infrastructure/iam-audit-logs.yaml
infrastructure/kms.yaml
k8s/Taskfile.yaml

As per the recommendations for NIST compliance in the GCP's security command center -
- Set key rotation period to 60 days
As per https://github.com/getsops/sops/issues/1135#issuecomment-1731811794, it shouldn't cause any issues to existing secrets when a key is rotated.
- Enable flow logs on subnet
I "clickops-ed" this because it's not a part of IaD, however, added the relevant flag to `k8s/Taskfile` command for future use.
- Enable IAM Audit logs
In addition to this, the `infrastructure/` directory is added to the cloudbuild trigger's ignored files.

Configure infrastructure for NIST compliance

---

infrastructure/api.yaml
k8s/server/base/django/deployment.yaml

- Enable API to view security posture dashboard for the cluster.
- Set `runAsNonRoot` and `allowPrivilegeEscalation` fields on the server pod based on the recommendations from the security posture dashboard.

Enable security posture

---

k8s/cnpg-system/kustomization.yaml
k8s/server/base/django/deployment.yaml

Even after merging https://github.com/PHACDataHub/cpho-phase2/pull/199, the security posture dashboard tagged `cnpg-controller-manager` and `server` deployments as misconfigurations under `pod container allows privilege escalations on exec`.
This was due to missing `allowPrivilegeEscalation` field for the `istio-proxy` container in the deployment spec (thanks to @simardeep1792 for pointing this). The alert technically is a false positive because the pods created by these deployments still have the `allowPrivilegeEscalation` field set. 
In any case, this PR explicitly sets the security context for `istio-proxy` containers to clean up the dashboard.

Add `allowPrivilegeEscalation` to deployments

---

k8s/server/ephemeral-instances/fix-cloud-trace-exporting-sync.yaml

Add resources to configure image update automation for `fix-cloud-trace-exporting` branch.

Add image update automation for ephemeral branch

---

infrastructure/iam-mapping.yaml
infrastructure/service-account.yaml
k8s/server/base/django/deployment.yaml
k8s/server/base/django/kustomization.yaml
k8s/server/base/django/service-account.yaml
k8s/server/overlays/prod/django/kustomization.yaml
k8s/server/overlays/prod/django/service-account.yaml

- Add a GCP service account for server deployment
Any permissions for the prod server pod must be assigned to this GCP service account.
- Add `roles/cloudtrace.agent` to fix cloud trace permission issues on server pod.
- Add K8s service account resource with appropriate annotations for workload identity and attach it to `server` deployment.
Note that the GCP service account annotation is only added to the **prod** server deployment and not the **ephemeral** one due to issues with binding workload identity user permission ephemerally as highlighted in https://github.com/PHACDataHub/cpho-phase2/pull/205#issue-2130770901. Ephemeral deployment pods will use the `server` K8s service account from their respective namespaces but, unlike prod, won't have any permissions on the cloud.

Add K8s and cloud permissions for server deployment

---

server/gunicorn.conf.py
server/server/open_telemetry_util.py

When new server pods are created in the cluster, they server container currently crashes and reboots once or twice before sorting itself out. Turns out this is related to (but not the solution to) our Cloud Traces having been broken ever since we switched to GKE. 
Details are in code comments, in short though we need to retrieve metadata from `metadata.google.internal` before we configure tracing. All google cloud compute resources (App Engine, Cloud Run, etc) can make calls to that internal metadata endpoint to get information about themselves, but there's a gotcha in GKE (of course). In GKE, the `metadata.google.internal` domain resolves to the cluster's own metadata server, but this metadata server can't accept traffic from new pods for "a few seconds" while the cluster sorts itself …

Fix server container crashing on newly created pods

---

k8s/server/base/postgres/pg-cluster.yaml

Reducing the log storage by changing the following parameters:
-       log_min_messages: "warning" # From "error" to "warning" to reduce informational messages
-       pg_stat_statements.track: top # From "all" to "top" to only track top-level statements
-       auto_explain.log_min_duration: '30s' # From "10s" to "30s" to reduce slow query logs
-       pgaudit.log: "ddl, role" # From "all, -misc" to specific events like DDL and role changes
-       log_connections: "off" # Reduced connection logs
-       log_disconnections: "off" # Reduced disconnection logs
-       log_hostname: "off" # Avoided logging hostnames
-       log_temp_files: "1024" # Log temp files larger than 1MB
-       log_lock_waits: "on" # Keep "on" if monitoring for lock waits
-       log_checkpoints: "on" # Keep "on" …

Reducing the log storage for CNPG

---

server/gunicorn.conf.py

Fixes:
1) gunicorn INFO logs being interpreted as ERROR logs in GCP
2) non-gunicorn log events, prior to app logging configuration being applied, not being output
See the code comment for details.

Fix gunicorn logging config

---

k8s/server/ephemeral-instances/main-sync.yaml

Add ephemeral build for main branch. 
The endpoint for this deployment would be `main.dev.hopic-sdpac.phac-aspc.alpha.canada.ca` due to the fact that resources for ephemeral builds are modified based on the `${BRANCH_NAME}` variable and therefore the virtual service configuration ends up being - https://github.com/PHACDataHub/cpho-phase2/blob/be228da5c53fbe65ba4cdf9f72becb31d90f23c5/k8s/server/overlays/ephemeral/django/virtual-service.yaml#L7
Having `dev-test` would break this convention. Unless, we have a separate branch for `dev-test` and spin up an env based off of it.

Add ephemeral build for `dev-test`

---

k8s/flux-system/alerts/alerts.yaml

Flux is spamming `Namespace/cnrm-system configured` on the slack updates channel and I can't seem to figure out the exact reason.
As a workaround, add the specific message to `exclusionList` key.

Add alert message to exclusion list

---

server/server/urls.py
server/tests/test_healthcheck.py

Pretty trivial. Health checks were triggering the unathenticated middleware and getting redirected to the login page. Marking the /healthcheck route as allowing unathenticated traffic prevents that, which reduces the general logging and telemetry noise from healthchecks as well as their impact on server resources.

Fix unauthenticated redirects from /healthcheck route

---

infrastructure/dns-zone.yaml

Add DNS zone for operations hopic endpoint i.e, `hopic-sdpac.data-donnes.phac-aspc.gc.ca`.
This is mostly to get SSO redirect set up with the new URL and test if DNS delegation works in the [upstream project](https://github.com/PHACDataHub/phac-dns).

Add DNS zone for ops

---

infrastructure/backend-service.yaml
infrastructure/kustomization.yaml
k8s/Taskfile.yaml
k8s/istio-ingress/xlb-gateway.yaml
k8s/istio-ingress/xlb-httproute.yaml
k8s/istio-ingress/xlb-policy.yaml

- Add `ComputeBackendService` resource to bind cloud armor policy to the backend service at an infrastructure level.
This resource was imported into KCC using the method described [here](https://cloud.google.com/config-connector/docs/how-to/import-export/export#exporting_example). This is a workaround as, [GKE Gateway API doesn't support configuring cloud armor when a regional XLB class is used](https://cloud.google.com/kubernetes-engine/docs/how-to/gatewayclass-capabilities#additional-services).
In the future, if cloud armor is still unsupported, it'd be better to have this link up configured while provisioning a regional security policy resource. KCC doesn't have this resource yet (See https://github.com/PHACDataHub/cpho-phase2/issues/218).
- Add `GCPBackendPolicy` to enable HTTP …

Configure cloud armor policy

---

server/server/settings.py

in prod, if someone logs out, they get the admin logout screen. If they log back in, it'll give them a 403 because the `?next` would go to the admin
Also fixes #146

fix logout url

---

k8s/server/base/postgres/pg-cluster.yaml

Enable Comprehensive SQL Logging in PostgreSQL Configuration
A change in the PostgreSQL configuration to enable logging of all SQL statements, including transactions. By setting `log_statement` to `'all'`, to enhance database's auditability and observability, ensuring capture comprehensive logs for all operations. This adjustment is crucial for troubleshooting and monitoring the database more effectively.
```yaml
log_statement: 'all' # Added to log all SQL statements, including transactions.
```

CNPG changes to log transactions

---

infrastructure/artifactregistry.yaml
infrastructure/cloudbuildtrigger.yaml
infrastructure/dns-zone.yaml
infrastructure/dnspolicy.yaml
infrastructure/kms.yaml
infrastructure/logging-bucket.yaml
infrastructure/proxy-subnet.yaml
infrastructure/service-account.yaml

Apparently when a dry run is executed by Flux's kustomize controller to apply resources, KCC _thinks_ that Flux is trying to modify an annotation (`cnrm.cloud.google.com/state-into-spec`) and denies the request because the value for that annotation is immutable. This consequently causes the reconciliation to fail.
This PR addresses the issue by explicitly adding the annotation to specific resources that KCC complains about. Some info on what this means and why it's not a disruptive change: https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/669#issuecomment-1339614273.
Essentially we're just setting a default value explicitly.

Fix sync for `infrastructure/`

---

infrastructure/api.yaml

Enable `networkmanagement.googleapis.com` to try out https://cloud.google.com/network-intelligence-center/docs/network-analyzer/overview?hl=en.

Enable network management API

---

infrastructure/backend-service.yaml
k8s/istio-ingress/xlb-policy.yaml

The upload indicator workflow freezes at an `Uploading data` state due to `504` gateway timeout. 
This PR increases the gateway timeout to 180 seconds so that the server has enough time to respond to the request. In addition to this, sets the `deletion-policy` annotation to `abandon` so that the lifecycle of the backend service is **only** managed by the gateway definition at `./k8s/istio-ingress/xlb-gateway` and not the IaD spec.
In general, if the gateway timeout needs to be edited:
- Pause `infrastructure` and `istio-ingress` flux ks reconciliations
- Delete the `ComputeBackendService` resource from the cluster
Due to the `deletion-policy` annotation this only deletes the cluster resource and doesn't affect the cloud resource
- Update`timeoutSec` at `./k8s/istio-ingress/xlb-policy` and …

Increase gateway timeout

---

server/gunicorn.conf.py
server/server/wsgi.py

Leaving our server pods on the minimal resources for now, but increasing the gunicorn workers per-pod (from 1 to 3). I expect this to fit based on pre-prod resource usage metrics and local testing, but it'll be something to keep an eye on. Due to the long running data upload requests, concurrency and scaling is necessary to keep the site from going unresponsive under regular use.
We'll also need to tune the cluster appropriately down the road (or maybe the per-pod resources), depending on if this puts the average CPU above the scaling threshold. Expect this to be fine though. @vedantthapa tagging you FYI.
Related #133

Pre-prod performance tuning

---

server/cpho/queries.py

updates global status for metadata status even if no data for bench or trend.
This is because sometimes indicators have no benchmarking or trend data but would still need to be approved

updates global status even if no data for bench or trend

---

k8s/server/overlays/prod/django/hpa.yaml

Increase in gunicorn worker count pushed us above pod scaling targets on memory usage, scaled us up to four server pods (which is not necessary). Fine tuning the HPA settings (or, worst case, lowering the workers per pod) should get us a more reasonable baseline.

Increase HPA memory averageUtilization target

---

k8s/server/ephemeral-instances/distroless-runtime-and-management-script.yaml

Add ephemeral env configurations for `distroless-runtime-and-management-image` branch.
Note that you'll need to update the `imagepolicy` comment at https://github.com/PHACDataHub/cpho-phase2/blob/distroless-runtime-and-management-image/k8s/server/overlays/ephemeral/django/deployment.yaml#L10 to `flux-system:distroless-server` to enable automated image updates.

distroless-runtime-and-management-image ephemeral env

---

k8s/server_management_session.sh

Part 1 of #64
Leverages `kubectl debug`, which lets you attach an ephemeral container to an existing container's process pool. This script just puts connecting to the cluster and selecting from the available server pods on-rails (also clones the server process' env vars to the attached debug/management shell, which is a minor trick but would be annoying to do manually every time).
As a follow up to this, we can strip down the prod image to the absolute minimum (possibly even "distroless") and add a dedicated management/debug image to the build pipeline. The script assumes we'll do that and push both containers with different names and the same per-commit/branch tags, to correlate the versions.
You can copy files to/from the running maintenance containers with `kubtectl cp`, similar in …

Server management session script

---

deploy/gcloud_env_vars.sh
k8s/server/base/django/deployment.yaml
k8s/server/overlays/ephemeral/django/deployment.yaml
server/server/settings.py

- Increase `initialDelaySeconds` to `135` to delay readiness checks so that the `server` pod has more time to startup
- Fix readiness probe request headers for ephemeral deployments
- Exempt the `healthcheck/` endpoint from secure ssl redirects to fix 301s in the `server` pod

Fix healthcheck 301s

---

k8s/Taskfile.yaml

Apparently GKE doesn't upgrade the nodes immediately once the control plane has been upgraded and internally it depends on a lot factors. Check [this](https://www.googlecloudcommunity.com/gc/Google-Kubernetes-Engine-GKE/Autopilot-node-now-stuck-in-Ready-SchedulingDisabled-state/m-p/515896) out, it took almost 3.5 days for the nodes to finish upgrading after the control plane was upgraded.
This PR sets a maintenance window for the cluster during work hours -> 10AM - 4PM ADT every week on Wed, Thu and Fri. Date and time info in the `gcloud` command is in UTC. The changes have already been applied.
See https://cloud.google.com/kubernetes-engine/docs/concepts/maintenance-windows-and-exclusions for details.
Relates to #182

Add maintenance window for GKE

---

k8s/server/overlays/prod/django/configmap.yaml

Looks like you did the same [here](https://github.com/PHACDataHub/cpho-phase2/compare/main...disable-login) @vedantthapa , we want this is in prod too. If you'd like to keep legacy login around to test the new domain, that's fine, as long as we turn this off when we finally launch.

fix: disable legacy login

---

k8s/server/base/django/deployment.yaml

Set `maxSurge` to `100%`. [Here's](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-surge) some info on what it implies. 
The idea is to roll out newer versions as quickly as possible so that the period where a K8s service load balances requests between old and new versions during a rolling update is reduced. Note that there might be a case where the existing nodes don't have the capacity for all the new pods, as a result, it'll still take a while for the new pods to be ready. In any case, it shouldn't be worse than what we have right now.
All other changes (`strategy.type` and `maxUnavailable`) are set to their defaults.

feat: configure `maxSurge` for server deployment

---

infrastructure/dns-zone.yaml

Since we've transitioned to the `prod` domain (https://github.com/PHACDataHub/cpho-phase2/pull/285) and have been stable for a while it'd be good to clean up the alpha DNS Managed Zone resource and it's record sets.

chore: deprecate alpha dns zone

---

k8s/README.md
k8s/configconnector-operator-system/autopilot-configconnector-operator.yaml

Upgrade KCC to v1.116.0.
Add cmd in `README.md` to clean up downloaded files after KCC upgrade.
Release notes: https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.116.0

chore: upgrade KCC to v1.116.0

---

infrastructure/dns-zone.yaml

Remove alpha DNS zones.
Although it was discussed in https://github.com/PHACDataHub/cpho-phase2/pull/311 that we'd want to keep the alpha zones around since SSO works, the [upstream dns service](https://github.com/PHACDataHub/dns) will soon be deprecated in favour of the [new one](https://github.com/PHACDataHub/phac-dns/tree/main) and therefore, the hopic subdomain on `phac-aspc.alpha.canada.ca` won't work.

chore: remove alpha DNS zones

---

k8s/server/base/postgres/pg-cluster.yaml

Switch off db-maintenance.
Clean up whitespaces.
K8s nodes were successfully upgraded to `1.28.7-gke.1026000`.

chore: switch off db-maintenance

---

k8s/README.md
k8s/cnpg-system/cnpg-crds.yaml
k8s/cnpg-system/kustomization.yaml

Upgrade CNPG operator to `1.23.1`
Update CNPG doc reference to `current`
Remove `securityContext` block since it's already set in the CRDs
Release notes: https://github.com/cloudnative-pg/cloudnative-pg/releases/tag/v1.23.1

chore: upgrade cnpg op `1.23.1`

---

infrastructure/artifactregistry.yaml
infrastructure/cloudbuildtrigger.yaml
infrastructure/dns-zone.yaml
infrastructure/dnspolicy.yaml
infrastructure/kms.yaml
infrastructure/logging-bucket.yaml
infrastructure/proxy-subnet.yaml
infrastructure/service-account.yaml
k8s/cnrm-system/context.yaml

- Set `stateIntoSpec` to `absent` in ConfigConnectorContext as [recommended in the docs](https://cloud.google.com/config-connector/docs/how-to/install-manually#addon-configuring).
Setting `absent` implies that KCC will skip populating unspecified fields into spec. I suspect this was the primary reason behind those flux spams about `ArtifactRegistryRepository/cnrm-system/hopic-k8s-images configured` in the slack channel.
- Remove manually added `state-into-spec` annotation for all resources except `ComputeAddress` due to [this](https://cloud.google.com/config-connector/docs/concepts/ignore-unspecified-fields#when_to_avoid_cnrmcloudgooglecomstate-into-spec_absent).
Relates to #227

feat: set `state-into-spec` in ConfigConnectorContext

---

server/cpho/jinja2/base.jinja2
server/cpho/model_factories.py
server/cpho/urls.py
server/cpho/views/changelog.py
server/tests/test_changelog.py

This is just the global changelog but just for the indicator-datum model, and you can add `?year=2023` on the URL to fitler to a particular year

feat: add year-filterable datum changelog

---

server/server/settings.py

Someone (*cough Todd cough*) just jammed up the login page for anyone on the VPN because they hit 3 failed attempts and the only fix is to manually delete axes records using CLI (or admin if you're already logged in)
We did something like this for ITAP. I don't remember what we set it to, but we haven't had a problem since. All logins can only be done via SSO so we don't have to worry about anyone trying 100 logins per day or whatever.

fix: raise axes failure limit to 100 (rather than 3)

---

k8s/server/ephemeral-instances/django5-sync.yaml

I copied the template and replaced the BRANCH_NAME with my targetted branch, `django5`
I need to test that my new branch doesn't mess with logging, because it's using a new version of structlog. I probably don't need much of a database.
A couple of questions,
1. Do I need to go and enable cloud-build, or is that only if I want to update this branch? If I push an update to this branch, it won't deploy anything?  
2. Is it important that my `django5` branch be ahead of prod? 
3. Will a new database be automatically created and migrated?
- I presume no scripts are run beyond the plain migrate?
4. If I want to SSH in, can I use the server-management-session script ?

feat: Add ephemeral environment django5

---

k8s/server/base/postgres/pg-cluster.yaml

Add `enablePDB` option and deprecate `nodeMaintenanceWindow` as per the release notes for [v1.23.0](https://github.com/cloudnative-pg/cloudnative-pg/releases/tag/v1.23.0).

feat: set enable PDB and deprecate node maintenance window

---

k8s/server/base/postgres/pg-cluster.yaml

Enable PDB on postgres cluster since the gke upgrade has been completed.
Relates to #356.

chore: enable pdb on pg cluster

---

k8s/configconnector-operator-system/autopilot-configconnector-operator.yaml

Upgrade KCC to v1.120.1
Release notes: https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.120.1

chore: upgrade KCC to v1.120.1

---

k8s/cert-manager/crds/cert-manager.yaml

Upgrade cert-manager to v1.15.2
Release notes: https://github.com/cert-manager/cert-manager/releases/tag/v1.15.2

chore: upgrade cert-manager to v1.15.2

---

k8s/configconnector-operator-system/autopilot-configconnector-operator.yaml

Release notes: https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.121.0

chore: upgrade kcc v1.121.0

---

architecture-diagram/README.md
architecture-diagram/architecture-k8s.d2
k8s/README.md

For some reason the architecture diagram logos weren't being rendered correctly in README.md, this PR adds a `png` for the diagram and updates any occurrences of `svg` to `png`.

fix: architecture diagram logos

---

server/cpho/views/infobase_export.py
server/tests/test_infobase_export.py

This PR achieves 3 things:
1. Only Approved data included in infobase export.
2.  If indicator data/ benchmarking or trend is submitted but indicator itself is not submitted, wont export any data related to that indicator
3. if indicator, indicator data, benchmarking, trend all submitted once, but later indicator has unsubmitted changes, in this case export will show the information from the last submitted version of the indicator in all 4 worksheets

fix: approved data in infobase export

---

server/requirements.txt

Reverts PHACDataHub/cpho-phase2#357
Wait for https://github.com/flavors/django-graphiql-debug-toolbar/issues/26 to get fixed before re-reverting this

Revert "chore: update debug-toolbar to support jinja templates"

---

server/cpho/jinja2/base.jinja2
server/cpho/jinja_helpers.py
server/requirements.txt
server/server/settings.py

Forces the yellow django error page on failed htmx requests, doing this in all the django projects.
Probably not super useful in this project, we only have one htmx request in the upload feature

fix: add htmx debugging
